trydjango19/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout')
]

trydjango19/posts/api/urls.py
from django.urls import path

from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostUpdateAPIView,
    PostDeleteAPIView,
    PostCreateAPIView
)

app_name = 'posts'

urlpatterns = [
    path('', PostListAPIView.as_view(), name='list'),
    path('create/', PostCreateAPIView.as_view(), name='create'),
    path('<slug>/', PostDetailAPIView.as_view(), name='detail'),
    path('<slug>/update/', PostUpdateAPIView.as_view(), name='update'),
    path('<slug>/delete/', PostDeleteAPIView.as_view(), name='delete'),
]

trydjango19/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('create/', views.post_create, name='create'),
    path('<slug>/', views.post_detail, name='detail'),
    path('<id>/update/', views.post_update, name='update'),
    path('<id>/delete/', views.post_delete, name='delete'),
]

trydjango19/trydjango19/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls',namespace='posts')),
    path('comments/', include('comments.urls',namespace='comments')),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('api/auth/token', obtain_jwt_token),
    path('api/users/', include('accounts.api.urls',namespace='users-api')),
    path('api/posts/', include('posts.api.urls',namespace='posts-api')),
    path('api/comments/', include('comments.api.urls',namespace='comments-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trydjango19/posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models.deletion import SET_NULL
from django.urls import reverse
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe

from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() == super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    return "{}/{}".format(instance.id, filename)

class Post(models.Model):
    title = models.CharField(max_length=120)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=SET_NULL, null=True)
    slug = models.SlugField(unique=True)
    read_time = models.IntegerField(default=0)
    image = models.ImageField(upload_to=upload_location,
        null=True,
        blank=True,
        height_field='height_field',
        width_field='width_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager() # 'objects' is 'Post.objects'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def get_api_url(self):
        return reverse('posts-api:detail', kwargs={'slug': self.slug})

    def get_markdown(self):
        return mark_safe(markdown(self.content))

    class Meta:
        ordering = ["-timestamp", "-updated"]

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    exist = qs.exists()
    if exist:
        new_slug = '%s-%s' % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        instance.read_time = get_read_time(html_string)

pre_save.connect(pre_save_post_receiver, sender=Post)

trydjango19/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget)
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

trydjango19/posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)
from rest_framework.generics import(
    ListAPIView, 
    RetrieveAPIView,
    RetrieveUpdateAPIView,
    UpdateAPIView,
    DestroyAPIView,
    CreateAPIView,
)

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly
)

from posts.models import Post
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination
from .serializers import PostListSerializer, PostDetailSerializer, PostCreateUpdateSerializer
from .permissions import IsOwnerOrReadOnly

class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    permission_classes = [AllowAny]
    search_fields = ['title', 'content', 'user__first_name']
    # URL examples
    # 1. Two depth search, first keyword is 'pyk', second keyword is 'edit':
    # http://127.0.0.1:8000/api/posts/?search=pyk&q=edit
    # 2. Search posts contain keyword 'pyk' and ordering in inverse title sequence  
    # http://127.0.0.1:8000/api/posts/?search=pyk&ordering=-title

    pagination_class = PostPageNumberPagination #PostLimitOffsetPagination

    def get_queryset(self, *args, **kargs):
        #queryset_list = super(PostListAPIView, self).get_queryset(*args, **kargs)
        queryset_list = Post.objects.all() # Same meaning as above line
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
                ).distinct()

        return queryset_list

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [AllowAny]

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsOwnerOrReadOnly]

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    # permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

trydjango19/posts/views.py
from urllib.parse import quote_plus

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post

def post_list(request):
    if request.user.is_staff or request.user.is_superuser:
        all_post_list = Post.objects.all()
    else:
        all_post_list = Post.objects.active()

    # Search Posts
    query = request.GET.get('q')
    if query:
        all_post_list = all_post_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
            ).distinct()

    paginator = Paginator(all_post_list, 5) #show 5 posts per page
    page_req_var = 'page'
    page = request.GET.get(page_req_var)
    context = {
        'title': 'Post lists',
        'page_req_var': page_req_var,
        'post_list': paginator.get_page(page),
        'today': timezone.now().date()
    }
    return render(request, 'posts/post_list.html', context=context)

def post_create(request):
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, 'create post succesfully')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'form': form
    }
    return render(request, 'posts/post_form.html', context)

def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff and not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    comments = instance.comments
    # equals to: Comment.objects.filter_by_instance(instance)

    initial_data = {
        'content_type': instance.get_content_type,
        'object_id' : instance.id
    }

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated:
        # c_type = form.cleaned_data.get('content_type')
        # content_type = ContentType.objects.get(model=ctype)
        # Above two steps will cause error, because of ContentType __str__ format
        # So I changed to this method as below
        content_type = ContentType.objects.get(model=instance.__class__.__name__.lower())

        parent_obj = None
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count()==1:
                parent_obj = parent_qs.first()

        obj_id = form.cleaned_data.get('object_id')
        content = form.cleaned_data.get('content')

        newComment, created = Comment.objects.get_or_create(
            user = request.user,
            content_type = content_type,
            object_id = obj_id,
            content = content,
            parent = parent_obj
        )

        return HttpResponseRedirect(newComment.content_object.get_absolute_url())

    context = {
        'instance': instance,
        'share_string': share_string,
        'comments': comments,
        'comment_form': form
    }
    return render(request, 'posts/post_detail.html', context=context)

def post_update(request, id=None):
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404

    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Update post succesfully')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': instance.title,
        'instance': instance,
        'form': form
    }
    return render(request, 'posts/post_form.html', context)

def post_delete(request, id=None):
    # Only allow staff group to create post
    if not request.user.is_staff and not request.user.is_superuser:
        raise Http404
    # Allow all user to create post
    # if not request.user.is_authenticated():
        # raise Http404

    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, 'delete post succesfully')
    return redirect('posts:list')

trydjango19/posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}Try Django 1.9{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'posts/css/base.css' %}">

    {% block head_extra %}{% endblock head_extra %}

</head>
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/zh_TW/sdk.js#xfbml=1&autoLogAppEvents=1&version=v5.0&appId=251980978929943"></script>
    
    {% include "posts/messages_display.html" %}

    <div class="container">
        <div class="col-sm-6 offset-sm-2">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="">Home</a></li>
                {% block post_detail_link %}
                {% endblock post_detail_link %}
    
                {% if not request.user.is_authenticated %}
                <li class="ml-auto"><a href="{% url 'accounts:register' %}">Register</a></li>|
                <li class=""><a href="{% url 'accounts:login' %}">Login</a></li>
                {% else %}
                <li class="ml-auto"><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% endif %}
            </ol>
        {% block content %}
            <h3>Extends from base.html</h3>
            <!-- use block.super to include parent html block content -->
        {% endblock content %}
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>
    
    <script type="text/javascript">
    $(document).ready(function(){
        $(".content-markdown").each(function(){
            var content = $(this).text();
            console.log(content);
            var markedContent = marked(content);
            console.log(markedContent);
            $(this).html(markedContent);
        })

        $(".post-detail-item img").each(function(){
            $(this).addClass("img-responsive");
            $(this).width('100%');
        })

        // dynamic update preview title
        var titleInput = $("#id_title");
        

        function setTitle(value){
            console.log(value)
            $("#title-preview").text(value);
        }
        setTitle(titleInput.val());

        titleInput.keyup(function(){
            setTitle(titleInput.val());
        })

        // dynamic update preview content
        var contentInput = $("#wmd-input-id_content");

        function setContent(value){
            if(value == undefined){
                return;
            }

            var markedContent = marked(value);
            $("#content-preview").html(markedContent);
            $("#content-preview img").each(function(){
                $(this).addClass("img-responsive");
                $(this).width('100%');
            })
        }
        setContent(contentInput.val());

        contentInput.keyup(function(){
            setContent(contentInput.val());
        })

        $(".comment-reply-btn").click(function(event){
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
            console.log("AAAAAAAAAAAA")
        });
    })
    </script>
</body>
</html>

trydjango19/posts/templates/posts/form.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ title }}</h1>

<div class="row">
    <div class="col-sm-6">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form | crispy }}
            <input type="submit" value="Login" />
        </form>
    </div>
</div>
{% endblock content %}

trydjango19/posts/templates/posts/messages_display.html
<div class="message">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

trydjango19/posts/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load urltify %}
{% load crispy_forms_tags %}

{% block title %}
{{ instance.title }} | {{ block.super }}
{% endblock title %}

{% block post_detail_link %}
<li class="breadcrumb-item"><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock post_detail_link %}

{% block content %}
    <h1>This is post_detail page</h1>

    <h6>{{ instance.title }}</h6>
    {% if instance.user.get_full_name %}
        <h6>Author: {{ instance.user.get_full_name }}</h6>
    {% endif %}

    <p>Read time: {% if instance.read_time <= 1 %}<1 minute{% else %}{{ instance.read_time}} minutes{% endif %}</p>

    <!-- <h6>{{ instance.timestamp }}</h6> -->
    <!-- <h6>{{ instance.updated }}</h6> -->
    <h6>
        Published: {{ instance.publish }}
        {% if instance.draft %}
            <small><span style="color:red">Draft</span></small>
        {% endif %}
    </h6>
    <hr>
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-resp">
    {% endif %}

    <div class="post-detail-item">{{ instance.get_markdown }}</div>

    <hr>
    <div class="row">
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width="" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    </div>
    <!-- demostrate two ways to implement share string -->
    <!-- {{ share_string | truncatechars:50 }}<br> -->
    <!-- {{ instance.content | urltify | truncatechars:50 }} -->
    <hr>
    <div class="share-to-social-media">
        <p>Share to:
        <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
            Facebook
        </a>,
        <a href="https://twitter.com/intent/tweet?text={{share_string}}%20{{ request.build_absolute_uri }}">
            Twitter
        </a>
        </p>
    </div>



    <div class="">
        <h3>Comments</h3><hr>

        {% if request.user.is_authenticated %}
        <form action="." method="POST">{% csrf_token %}
            {{ comment_form | crispy }}
            <input type="submit" class="btn btn-default" value="Leave a comment">
        </form>
        {% else %}
        <h4>You must login to comment</h4>
        <hr>
        {% endif %}

        {% for comment in comments %}
            <blockquote class="blockquote">
                <p class="mb-0">{{ comment.content }}</p>
                <footer class="blockquote-footer">via {{ comment.user }} | {{ comment.timestamp | timesince }} ago
                    {% if comment.children.count > 0 %}
                     | {{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}
                    {% endif %}
                    <a href="#" class="comment-reply-btn">Reply</a> | 
                    <a href="{{ comment.get_absolute_url }}">Thread</a>
                </footer>
                
                <div class="comment-reply">
                {% for child_comment in comment.children %}
                <blockquote class="blockquote text-right">
                    <p class="mb-0">{{ child_comment.content }}</p>
                    <footer class="blockquote-footer">via {{ child_comment.user }} | {{ child_comment.timestamp | timesince }} ago</footer>
                </blockquote>
                {% endfor %}
                
                {% if request.user.is_authenticated %}
                <form action="." method="POST">{% csrf_token %}
                    {{ comment_form | crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input type="submit" class="btn btn-default" value="Reply">
                </form>
                {% else %}
                <h4>You must login to comment</h4>
                <hr>
                {% endif %}
                </div>

            </blockquote>
            <hr>
        {% endfor %}
    </div>
    <div class="row">
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="" data-numposts="5"></div>
    </div>

{% endblock content %}

trydjango19/posts/templates/posts/post_form.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock head_extra %}

{% block content %}
<h1>This is post_form page</h1>
<hr>
<div class="row">
    <div class="col-sm-6">
        <h3>Preview</h3>
        <div class="content-preview">
            <h6 id="title-preview"></h6>
            <p id="content-preview"></p>
        </div>
    </div>
    <div class="col-sm-6">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form | crispy }}
            <input type="submit" value="Create Post" />
        </form>
    </div>
</div>
{% endblock content %}

trydjango19/posts/templates/posts/post_list.html
{% extends "posts/base.html" %}

{% block content %}
    {{ block.super }} <!--get parent template content -->
    <h1>This is {{ title }} page</h1>

<div>
    <form method="GET" action="">
        <div class="col-sm-6">
        <div class="input-group">
            <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}">
            <!-- <input class="btn btn-default" type="submit" value="Search"> -->
            <button class="btn btn-default" type="submit"><i class="fa fa-search"> Search</i></button>
        </div>
        </div>
    </form>
    <hr>
</div>

    {% for post in post_list %}
    <div class="card">
        {% if post.image %}
        <img class="card-img-top" src="{{ post.image.url }}">
        {% endif %}
        <div class="card-body post-detail-item">
            <h2 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <!-- <small> | {{ post.timestamp }}</small> -->
            </h2>
            {% if post.user.get_full_name %}<h6>Author: {{ post.user.get_full_name }}</h6>{% endif %}
            <!-- <h6 class="card-text">Updated: {{ post.updated | timesince }} ago</h6> -->
            <h6>Published: {{ post.publish }}
                {% if post.draft %}
                    <small><span style="color:red">Draft</span></small>
                {% endif %}
                {% if post.publish > today %}
                    <small><span style="color:red">Not publish Yet</span></small>
                {% endif %}
            </h6>
            {{ post.get_markdown | truncatechars_html:50 }}
            <a href="{{ post.get_absolute_url }}" class="btn btn-primary">View...</a>
        </div>
        <hr>
    </div>
    {% endfor %}

    <div class="pagination">
        <span class="step-links">
            {% if post_list.has_previous %}
                <a href="?{{ page_req_var }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo; first</a>
                <a href="?{{ page_req_var }}={{ post_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
            </span>
    
            {% if post_list.has_next %}
                <a href="?{{ page_req_var }}={{ post_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
                <a href="?{{ page_req_var }}={{ post_list.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock content %}